### ISSUE TITLE
Phenotyper json

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#122]
* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**
In json file from Phenotyper (sample.preprocessed.phenotype.json) field relatedDrugs is empty. I used this field in previous versions (e.g. v1.8). For now it's only available in json from Reporter.

Now it looks like:
 

>         "relatedDrugs": [] 

instead of:

>         "relatedDrugs": [
>           {
>             "name": "allopurinol",
>             "id": "PA448320"
>           }
>         ]

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

`java -jar pharmcat-2.1.2-all.jar -vcf sample.vcf -bf sample -o $KOHORT_DIR/Pharmcat_output/`

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.1.2

**Comment by whaleyr** [comment]
This is expected behavior.

By default, PharmCAT runs the NamedAlleleMatcher, then the Phenotyper, then the Reporter. The drug information is not added until the Reporter step. If you only run PharmCAT up do the Phenotyper step then you'll missing loading information about drugs and their associated genes.
