### ISSUE TITLE
Cannot use Named Allele Matcher 201 feature correctly

### ISSUE THREAD

**Issue by amanpruthi15** [PharmGKB/PharmCAT#124]
* **Do you want to request a *feature* or report a *bug*?**

A feature

* **What is the current behavior?**

I want to exclude most of the allele calls for a given set of genes and only include a few of those. I have tried editing the exemption.json file as it is suggested in "Named Allele Matcher 201". I added the parameter -matcherHtml to create pharmCAT reports but it is still including the alleles that I don't want.

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

* **What is the expected behavior?**

To report alleles not present in the exemptions.json

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.1
  - JDK Version: [ JDK8 | OpenJDK | etc ] - openjdk 17.0.5 2022-10-18
  - Environment: [ Windows | macOS | Linux distro | etc ] - Linux (computer cluster)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by markwoon** [comment]
Per the documentation, this feature only works if you're generating your own named allele definitions.

PharmCAT does not condone eliminating large number of named alleles from being called as you described in your email to the mailing list.

By removing named alleles you are forcing PharmCAT to produce possibly incorrect calls, and is the antithesis of our efforts to produce completely transparent reports regarding what was tested.

If you are intending to use the reports for any clinical purpose then this can lead to disastrous results.

Because we don't support this use of PharmCAT, we have no plans on improving the documentation.  However, the code is freely available for you to figure out how to do it.  But please, please use it responsibly.
