### ISSUE TITLE
PGx VCF output missing information in latest versions

### ISSUE THREAD

**Issue by alavertu** [PharmGKB/PharmCAT#14]
In the previous version of pharmcat, the precompiled [ PharmCAT jar](https://github.com/PharmGKB/PharmCAT/releases/download/v0.2.0/pharmcat-0.2.0-all.jar), running the command below would export a complete vcf containing all the variants PharmCAT uses to make allele calls. 

java -cp pharmcat-*-all.jar org.pharmgkb.pharmcat.definition.ExtractPositions -o pgx.vcf

In the latest version, this extraction call outputs a vcf with missing ref and alternate allele information. 

This malformed file results in issues when attempting to use this vcf in other downstream applications, such as variant calling with GATK. 

Here's an example of a missing line:
`chr1	97740602	rs41309171	.	.	.	PASS	PX	GT	0/0`

An example of a complete line:
`chr1	97082391	rs67376798	T	A	.	PASS	PX=DPYD:Reference[10]isT,DPYD:c.2846A>T[1]isA	GT	0/0`

A list of all missing sites is attached.
[missing_vcf_sites.txt](https://github.com/PharmGKB/PharmCAT/files/1849083/missing_vcf_sites.txt)

**Comment by whaleyr** [comment]
Investigating...

But first thing I would recommend is [building from source](https://github.com/PharmGKB/PharmCAT/wiki/Running-PharmCAT), that packaged release is super old.

**Comment by whaleyr** [comment]
Just pushed a fix. The problem was with alleles that are used in the final report but are not part of the allele definitions themselves. These extra positions will use the reference sequence for their reference allele and then not list any alts since we have no expectation of what to find there.

[An example output with this new fix](https://gist.github.com/eec535b50609d87ce39ee6454d43829c)
