### ISSUE TITLE
Version 2.6.0 missing on Docker Hub

### ISSUE THREAD

**Issue by kuanyili** [PharmGKB/PharmCAT#148]
See https://hub.docker.com/r/pgkb/pharmcat/tags

**Comment by BinglanLi** [comment]
Thank you for reporting this. We are working on the issue.

**Comment by BinglanLi** [comment]
Thank you for your patience. We are working on the fix and aiming at publishing a working docker image by the end of this month.

**Comment by kuanyili** [comment]
Thanks for letting us know. :)

**Comment by krukanna** [comment]
Hi, do you know maybe exact publication date?

**Comment by BinglanLi** [comment]
We are planning on a new release with updates in these two weeks.

**Comment by cariaso** [comment]
I suggest that
https://hub.docker.com/layers/pgkb/pharmcat/2.7.0/images/sha256-cb357692a946689882b447940c692419520a5a42f9ada776380123d4a1eb532e?context=explore
sufficiently resolves this

**Comment by kuanyili** [comment]
Thanks for the update about version 2.7.0.

However, I still think version 2.6.0 should be there in the registry. In science, reproducibility matters, keeping images of previous versions definitely improves it.

Even if there are known bugs in previous releases, it is better to have them around for the sake of reproducibility and consistency.

**Comment by markwoon** [comment]
2.6.0 is available, just not via Docker.  If you need reproducibility, just download the one distributed on GitHub.

Otherwise, due to the way we build the Docker image, there's no easy way for me to produce a 2.6.0 image - because we had to change something to fix the build, and that means 2.6.0 as a snapshot it time cannot be reproduced.  Otherwise, we would already have uploaded it.

**Comment by kuanyili** [comment]
So there's a bug in 2.6.0 that stopped the Docker image from building, missed that, silly me. 😅

Thank you all for working out a fix, much appreciated!
