### ISSUE TITLE
UGT1A1, VKORC1  - Updated version change in haplotype values

### ISSUE THREAD

**Issue by snehaleela** [PharmGKB/PharmCAT#149]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

UGT1A1 - Genotype output - *1/*1 -  For newer version of pharmcat - 2.6.0
VKORC1 - Genotype output - rs9923231 reference(C)/rs9923231 reference(C) -  For newer version of pharmcat - 2.6.0

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

UGT1A1 - Genotype output - *80+*28/*80+*28 -  For older version of pharmcat - 2.1.2
VKORC1 - Genotype output - rs9923231 reference(C)/rs9923231 reference(T) -  For newer version of pharmcat - 2.6.0
* **What is the expected behavior?**

UGT1A1 - Genotype output - *80+*28/*80+*28 
VKORC1 - Genotype output - rs9923231 reference(C)/rs9923231 reference(T) 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: ???
  - JDK Version: [ JDK8 | OpenJDK | etc ]
  - Environment: [ Windows | macOS | Linux distro | etc ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by whaleyr** [comment]
Can you supply an example VCF file that demonstrates the problem?

**Please make sure this is not an actual sample file with any personally identifiable information and truncated to as small of a dataset as possible.**

**Comment by snehaleela** [comment]
Hi we have used the VCF's provided in Pharmcat github page only : 
For VKORC1 - 
-1639A-1639A.vcf  - rs9923231 reference(C)/rs9923231 reference(C)
-1639G-1639A.vcf  - rs9923231 reference(C)/rs9923231 reference(T) - Correct
-1639G-1639G.vcf  - rs9923231 reference(C)/rs9923231 reference(C)

**Comment by whaleyr** [comment]
I'm still having a hard time understanding.

The files you're pointing out are [resource files](https://github.com/PharmGKB/PharmCAT/tree/development/src/test/resources/org/pharmgkb/pharmcat/haplotype/VKORC1) used for running [a unit test in the codebase](https://github.com/PharmGKB/PharmCAT/blob/development/src/test/java/org/pharmgkb/pharmcat/haplotype/NamedAlleleMatcherVkorc1Test.java).

In those unit tests you can see the `expectedMatches` List contains what we expect each file to report. All those unit tests pass in the current version of PharmCAT. Those diplotype strings are what we expect the calls to be.

`rs9923231 reference(C)/rs9923231 reference(T)` is not correct because `reference(T)` doesn't make sense. `T` is the variant allele at this position so it would be labeled as variant, not reference. The correct call is `rs9923231 reference (C)/rs9923231 reference (C)`.

Backing up a bit, can you describe what you're trying to do at a higher level? Are you trying to run existing unit tests in PharmCAT for yourself? Are you taking out those unit test resource files and trying to use them in a different context? Knowing what you're trying to do may help us give you better feedback.

**Comment by markwoon** [comment]
Closing issue due to insufficient information.

@snehaleela We need more information in order to help you.  Feel free to re-open this issue if you can provide the details Ryan is asking for above.
