### ISSUE TITLE
CFTR outside calls diplotype

### ISSUE THREAD

**Issue by Bioinf-usr** [PharmGKB/PharmCAT#161]
Hi,

What is the accepted genotype for CFTR while supplying from an outside calls file? I am trying with `Reference/Reference` but somehow pharmcat is unable to translate into the respective phenotype. I am using the latest version of pharmcat 2.8.3.

<img width="842" alt="Screenshot 2023-11-06 at 16 33 53" src="https://github.com/PharmGKB/PharmCAT/assets/77389502/98ae938c-3ec1-4933-ab90-c93008b1eee9">

Whereas when I try to call the phenotype directly using pharmcat by providing the vcf, it is showing the same genotype `Reference/Reference` but now it is translated into the corresponding phenotype.

<img width="1172" alt="Screenshot 2023-11-06 at 16 34 56" src="https://github.com/PharmGKB/PharmCAT/assets/77389502/52244285-7e1c-4188-85bf-3f047a05af0f">

Please let me know if I'm missing something here?

**Comment by whaleyr** [comment]
Hi, thanks for bringing this up. Two things to know:

1) The list of valid allele and phenotype names for all genes can be found on the [Phenotypes List](https://pharmcat.org/Phenotypes-List/) page and there is a [section for CFTR](https://pharmcat.org/Phenotypes-List/#cftr) that lists `ivacaftor non-responsive CFTR sequence` as a valid allele.
2) You ran into a bug in the system which prevented `ivacaftor non-responsive CFTR sequence` from working properly in outside calls. The system was "helpfully" stripping gene symbols from allele names to help normalize them before attempting to match. However, in this case it caused a valid allele name to break and not match properly. I've removed the code to strip the gene symbol and now it will work properly.

CFTR is a bit of an odd duck due to CPIC not using an allele with the name `Reference`. We do reassign `ivacaftor non-responsive CFTR sequence` to `Reference` for the final report since we believe that's a more intuitive value to display for people reading it.

This fixed on the development branch and will be included in the next release of PharmCAT.

**Comment by Bioinf-usr** [comment]
Thanks for looking into it. Regarding point 1, I have also noticed it and tried changing the `Reference` to `ivacaftor non-responsive CFTR sequence` as described in the documentation. However, due to the bug mentioned in point 2, I still didn't manage to generate the correct phenotype. 

Looking forward to the next release :)

**Comment by markwoon** [comment]
This should be fixed now.
