### ISSUE TITLE
CPIC query via PharmGKB API

### ISSUE THREAD

**Issue by kokyriakidis** [PharmGKB/PharmCAT#25]
Hi @whaleyr !

Is there a way to retrieve the guidelines in PharmCAT's report using a query to the PharmGKB API?

I want to retrieve the table produced when user inserts the alleles in this page for e.g.
```
https://www.pharmgkb.org/guidelineAnnotation/PA166105000
```

Do I have to use this function? I always get no content and I might fill in wrong ID. What is the proper id for the above guideline?
```
https://api.pharmgkb.org/swagger/#!/report/post_report_guideline_id_annotations
```

**Comment by whaleyr** [comment]
We are seeking funding to maintain and update PharmCAT since our initial release which is based on CPIC guidelines from over a year ago. Unfortunately, we haven't had the resources to update PharmCAT to the newest CPIC guideline publications and updates.  The CPIC guideline annotations on the PharmGKB website that you point to are not available for distribution because in some cases PharmGKB curators have had to make some assumptions when interpreting the guidelines for the drop-down menus.  We prefer people directly consult the information from CPIC itself. Currently, CPIC is building a database which will contain all guideline information and mappings but until then, all of the tables used to construct the PharmGKB annotations are found on the CPIC website at http://cpicpgx.org in the guideline section.
