### ISSUE TITLE
java.net.UnknownHostException: www.biodas.org

### ISSUE THREAD

**Issue by muzic194** [PharmGKB/PharmCAT#32]
Hello,

I'd like to obtain updated pgx.vcf. Following instructions on https://github.com/PharmGKB/PharmCAT/wiki/Preparing-VCF-Files I've run:

```
java -cp pharmcat-*-all.jar org.pharmgkb.pharmcat.definition.ExtractPositions -o pgx.vcf
```

but the resulting pgx.vcf has lot less lines than original one that was created at the end of 2019(around 40% less). And I get lots of `java.net.UnknownHostException: www.biodas.org`.

* **What is the expected behavior?**

Command runs successfully without errors and there are comparable number of variants in the vcf fil

* **What is the motivation / use case for changing the behavior?**

We'd like to keep database used by PharmCAT up to date

* **Please tell us about your environment:**
 
We clone this repository (master branch) and use Java 8.

Thank you!

**Comment by whaleyr** [comment]
The `biodas.org` problem is due to UCSC DAS server giving XML with an invalid DTD. Eventually we can replace the DAS server with NCBI resources. However, for now, I've turned off DTD validation in a recent [commit to the development branch](https://github.com/PharmGKB/PharmCAT/commit/32d43affdebbefe5b80d90ea997d4d619665fe9b). This will be part of the next release but if you check out the development branch you can compile from source and use it now.
