### ISSUE TITLE
could i use my 23andme data to apply this assay?

### ISSUE THREAD

**Issue by Philips-omica-io** [PharmGKB/PharmCAT#49]
hello,i did a basic genotyping with 23and me, i would like procces my data myself and i woul like know if a could use this tool for pharmacogenomics, my data is a vcf with chrom, rside , position and alleles, what kind of procces i have to do for run pharmcat?

**Comment by whaleyr** [comment]
Any genomic data used as input for PharmCAT [must be in VCF format](https://github.com/PharmGKB/PharmCAT/wiki/VCF-Requirements). We do not supply any tools for transforming 23andMe data into VCF format suitable for use with PharmCAT and we haven't done any testing to know whether it's technically possible.

We specify VCF as the input format because it is widely adopted by the genomics community and there are many many tools available for people to use with their particular data set. There are many many caveats and intricacies to these tools and datasets so please exercise caution.

**Comment by Philips-omica-io** [comment]
que tipo de análisis de laboratorio recomiendan efectuar para poder utilizar esta herramienta?

**Comment by Philips-omica-io** [comment]
What kind of lab tests do you recommend doing in order to use this tool?

**Comment by whaleyr** [comment]
We can't make any recommendation for particular lab tests. However, whole genome sequences are best. We've [updated our FAQ](https://github.com/PharmGKB/PharmCAT/wiki/FAQs#can-i-use-my-consumer-genetic-testing-data-23andme--ancestryorg--etc-with-pharmcat) and we're updating [other parts of our documentation](https://github.com/PharmGKB/PharmCAT/wiki/VCF-Requirements) to be more specific about our expectations for input.
