### ISSUE TITLE
Compiling project to jar

### ISSUE THREAD

**Issue by jkaefer** [PharmGKB/PharmCAT#54]
I am attempting to compile the project code and convert it to a jar artifact in Intellij. I'm able to generate a jar file that prompts for argument specification:

![thumbnail_image](https://user-images.githubusercontent.com/33101879/128538500-579a3c06-b757-48dc-99cf-e32aad63c3ed.png)

Upon providing a vcf file and an output path an error is generated regarding a function in a google library:

![image](https://user-images.githubusercontent.com/33101879/128538667-ec387a27-bf46-4a1e-a59f-5bc38ace0b3e.png)

Upon decompiling the jar file it seems the required java class is present along with the function posing the issue. Here is the xml file used for the compilation of the jar in case you could let me know a file is being included that shouldn't be: 

[PharmCAT-main-xml.txt](https://github.com/PharmGKB/PharmCAT/files/6946733/PharmCAT-main-xml.txt)

Thank you for your help.

**Comment by whaleyr** [comment]
The officially supported way to build the jar is documented on our [Building PharmCAT](https://github.com/PharmGKB/PharmCAT/wiki/Building-PharmCAT#releasing) document. You should be using Gradle to build it.

```shell
./gradlew shadowJar
```

That will make the "fat" jar with dependencies included.

It's hard to give specific advice about building in your instance of IntelliJ because I don't know how you have it set up. I can say that the repo is a Gradle project and IntelliJ should be able to auto-configure based on the gradle settings, assuming that you have the Gradle plugin installed and enabled. If that's true, then you should have a Gradle panel in the IDE where the `shadowJar` Task is available to run.

<img width="360" alt="Screen Shot 2021-08-06 at 9 54 43 AM" src="https://user-images.githubusercontent.com/329004/128545477-89c89a7f-dc9e-4c51-98f9-91a9f4abbed6.png">

**Comment by jkaefer** [comment]
Thank you for the prompt response. Would you be able to provide an example pharmcat.properties file, would I also need to register the email for my google service account with PharmGKB/PharmCat in order to gain access to the data? If so how would I do that?

**Comment by whaleyr** [comment]
All data needed to run PharmCAT is already part of the repo. You don't need to run the `updateData` task, that's really just for us to update the data in the repo.

If you're interested in looking at the data that supports PharmCAT, look in the [resources directory](https://github.com/PharmGKB/PharmCAT/tree/main/src/main/resources/org/pharmgkb/pharmcat).

**Comment by jkaefer** [comment]
@whaleyr The output jar I'm finding is titled pharmcat-0.0.0-all.jar, is this the latest version? I assume it it, just wanted to make sure.

**Comment by whaleyr** [comment]
You can see releases on our [releases page](https://github.com/PharmGKB/PharmCAT/releases).

If you downloaded the source code as a zip or tarball the jar will not be tagged with the latest version number because that information comes from git. If you want to fix that then you need to do a git checkout of the repo then build from there.
