### ISSUE TITLE
Reporter module is missing "-c" option to take in the named allele matcher JSON

### ISSUE THREAD

**Issue by BinglanLi** [PharmGKB/PharmCAT#72]
* **Do you want to request a *feature* or report a *bug*?**
 *bug*

* **What is the current behavior?**
PharmCAT reporter does not have "-c" option. 

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
~/jdk/jdk-14/bin/java -cp pharmcat-1.1.0-all.jar org.pharmgkb.pharmcat.reporter.Reporter -h
usage: Reporter
 -h,--help                          print this message
 -j,--output-json <file-path>       optional, file path to write JSON data
                                    to
 -o,--output-file <file-path>       file path to write HTML report to
 -p,--phenotyper-file <file-path>   phenotyper output JSON file
 -t,--title <title>                 optional, text to add to the report
                                    title
 -v,--verbose                       enable verbose output

* **What is the expected behavior?**

Reporter should have a *-c* option to take the JSON call file from the Named Allele Matcher. 

* **Please tell us about your environment:**
  
  - PharmCAT Version: v1.1.0
  - JDK Version: [ JDK8 | OpenJDK | etc ]: OpenJDK 14
  - Environment: [ Windows | macOS | Linux distro | etc ] Linux x64

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

Here is the screen shot of error message when running reporter.
![image](https://user-images.githubusercontent.com/17301572/137566293-f506b81e-e3f4-4915-8283-8e042e2ea84a.png)

**Comment by whaleyr** [comment]
I'm guessing you're saying the Reporter should have a `-c` option because it was in the wiki documentation. That was an error and I've updated the wiki to reflect the actual CLI flags for the Reporter. 

The Reporter can't actually take input straight from the NamedAlleleMatcher. It has to go through the Phenotyper first and then it can take the Phenotyper output as input. So either run the Phenotyper as a middle step or, what I prefer, just run the whole PharmCat tool and that way you can get all data and outputs.
