### ISSUE TITLE
Docker running problem

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#89]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
I am not able to run the docker in nextflow. I tried also independently and no result.
Standalone:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./PharmCAT_VCF_Preprocess.py\": permission denied": unknown.
```

And in nextflow:
```Command error:  .command.sh: line 2: PharmCAT_VCF_Preprocess.py: command not found  ```

I don't know how to bind directories to make it work. 

* **Please tell us about your environment:**
  
  - PharmCAT Version: 1.5.1 docker version
  - JDK Version: [ JDK8 | OpenJDK | etc ]
  - Environment: Linux

**Comment by krukanna** [comment]
I have checked and still got this problem
My command inside nextflow script and occured error: 

```
./PharmCAT_VCF_Preprocess.py --input_vcf cohort.genotyped.all.vcf.gz --ref_seq reference.fasta --output_prefix diag

Command error:
  .command.sh: line 2: ./PharmCAT_VCF_Preprocess.py: No such file or directory
```

But when I use docker image standalone I don't have previous error, now docker cannot find input vcf.
```
docker run --rm -v /home/bioinf/:/pharmcat/data/ pgkb/pharmcat_cor1 ./PharmCAT_VCF_Preprocess.py \
--ref_seq /data/genom/reference.fasta \
--input_vcf /data/PharmCAT/docker/cohort.genotyped.all.vcf.gz \
--output_prefix pharmcat_cor1

Error:
Cannot find data/PharmCAT/docker/cohort.genotyped.all.vcf.gz
```

**Comment by markwoon** [comment]
I'm not familiar with nextflow, so I'm not sure how the script is being called exactly, but the error is that it cannot find the preprocessor script.  Are you sure it's in the directory it's being called from?  That `./` in front of `PharmCAT_VCF_Preprocess.py` means it needs to be in the same directory...

Again, I'm not sure what your directory layout is, but the error you're getting with Docker also indicates that it cannot find the file.  Since you're mounting `/home/bioinf` as `/pharmcat/data`, you need to provide relative paths from the `/pharmcat` directory.

Assuming `cohort.genotyped.all.vcf.gz` is in `/home/bioinf` then try:

```
docker run --rm -v /home/bioinf/:/pharmcat/data/ pgkb/pharmcat_cor1 ./PharmCAT_VCF_Preprocess.py \
--ref_seq /data/genom/reference.fasta \
--input_vcf data/cohort.genotyped.all.vcf.gz \
--output_prefix pharmcat_cor1
```

I would also assume that you're going to get errors on the path to reference.fasta.  My first question is, are you sure you need it?  Are you using something other than GRCh38?  If not, the dockerized preprocessor comes with the reference, so you don't need to provide it.

If you do need to provide it, then that path looks incorrect as well.  If it's in `/home/bioninf/genom`, then leave off that leading `/` (i.e. `data/genom/reference.fasta`).  Also check if you've got a spelling error with "genom".

**Comment by markwoon** [comment]
Closing due to lack of response.
